// Generated by scripts/gen-lesson-index.mjs — do not edit by hand.
// Run `npm run gen:lessons` after adding or removing a lesson file.

import type { Lesson } from "@/types/lesson";
import lesson1Data from "./lesson_1.json";
import lesson2Data from "./lesson_2.json";
import lesson3Data from "./lesson_3.json";
import lesson4Data from "./lesson_4.json";
import lesson5Data from "./lesson_5.json";
import lesson6Data from "./lesson_6.json";
import lesson7Data from "./lesson_7.json";
import lesson8Data from "./lesson_8.json";
import lesson9Data from "./lesson_9.json";
import lesson10Data from "./lesson_10.json";
import lesson11Data from "./lesson_11.json";
import lesson12Data from "./lesson_12.json";

export const LESSONS = [
  lesson1Data, // 01_anwaa_al_kalimat
  lesson2Data, // 02_aqsaam_al_fil
  lesson3Data, // 03_al_mudhakkar_wal_muannath
  lesson4Data, // 04_al_mufrad_wal_muthanna_wal_jam
  lesson5Data, // 05_al_kalaam
  lesson6Data, // 06_al_mabni_wal_murab
  lesson7Data, // 07_anwaa_al_binaa
  lesson8Data, // 08_al_mabni_min_al_huruf_wal_afaal
  lesson9Data, // 09_al_asmaa_al_mabniyya
  lesson10Data, // 10_anwaa_al_irab
  lesson11Data, // 11_irab_al_muthanna_wal_jam
  lesson12Data, // 12_irab_al_fil_al_mutall
] as unknown as Lesson[];
