// Generated by scripts/gen-lesson-index.mjs — do not edit by hand.
// Run `npm run gen:lessons` after adding or removing a lesson file.

import type { Lesson } from "@/types/lesson";
import lesson1Data from "./lesson_1.json";
import lesson2Data from "./lesson_2.json";
import lesson3Data from "./lesson_3.json";
import lesson4Data from "./lesson_4.json";

export const LESSONS = [
  lesson1Data, // 01_anwaa_al_kalimat
  lesson2Data, // 02_aqsaam_al_fil
  lesson3Data, // 03_al_mudhakkar_wal_muannath
  lesson4Data, // 04_al_mufrad_wal_muthanna_wal_jam
] as unknown as Lesson[];
